### ISSUE TITLE
[1.21.6-NeoForge] NF 21.6.6-beta introduces FML api changes which breaks KFF

### ISSUE THREAD

**Issue by Ellie-McQuinn** [thedarkcolour/KotlinForForge#123]
https://github.com/neoforged/FancyModLoader/pull/290 removes the bus parameter from the `@EventBusSubscriber` annotation which causes the registration of "Automatic Kotlin subscribers" to fail.

```
[15:18:25] [modloading-worker-0/ERROR] [th.ko.ne.LoggerKt/LOADING]: Failed to register Automatic Kotlin subscribers. ModID: expandedstorage, class dev.compasses.expandedstorage.NeoForgeClient
java.lang.NoClassDefFoundError: net/neoforged/fml/common/EventBusSubscriber$Bus
```

**Comment by unilock** [comment]
This applies to NF 21.1.181 as well.

**Comment by Ellie-McQuinn** [comment]
I'd suggest tracking that issue with #124 as the problem area is slightly different... The current version works on 1.21.1 if you don't use the `@EventBusSubscriber` annotation where as 1.21.6 any KFF mod will fail to launch.
